### ISSUE TITLE
Equality filter doesn't work with nested array

### ISSUE THREAD

**Issue by hammer2j2** [h2non/jsonpath-ng#6]
Been at this all day from different angles trying to figure out why the filter isn't working.

```python
>>> data
{'accounts': [{'regions': ['us-east-1', 'sa-east-1', 'ap-east-1'], 'vpcs': [{'subnets': ['10.0.0.0/24', '10.0.1.0/24'], 'region': 'us-east-1', 'name': 'main'}, {'subnets': ['172.1.1.0/24', '172.1.2.0/24'], 'name': 'vpc1'}], 'name': 'galluptest'}, {'regions': ['us-west-2', 'sa-east-1'], 'vpcs': [{'subnets': ['10.1.1.0/24', '10.1.2.0/24'], 'region': 'us-west-2', 'name': 'default'}, {'subnets': ['172.16.1.0/24', '172.16.2.0/24'], 'name': 'alt'}], 'name': 'ztest'}]}

>>> 
>>> p = parse('$.accounts[*][?name = "ztest"].name')
>>> p.find(data)
[]
>>> p
Child(Child(Child(Child(Root(), Fields('accounts')), Slice(start=None,end=None,step=None)), Filter([Expression(Fields('name') = u'ztest')])), Fields('name'))

>>> [match.value for match in p.find(data)]
[]
>>> 
```

What am doing wrong?

Thanks.

**Comment by tomas-fp** [comment]
Try using `from jsonpath_ng.ext import parse` instead of `from jsonpath_ng import parse`.

**Comment by tomas-fp** [comment]
Alright, this looks like a legit bug. I don't know when I could fix, so feel free to send a PR in the meantime.

Alternatively, in order to solve your issue, you can split the process in two steps:
- First, use a more simple filter `parse('$.accounts[*].name')` that would give you the nodes to you want.
- Then, use a custom filter logic to perform the filtering, such as: `filter(matches, nodes)`.

That should do the job for you.

**Comment by hammer2j2** [comment]
Thanks for the quick follow-up and guidance.

**Comment by michaelmior** [comment]
I believe the path you want is `'$.accounts[?name = "ztest"].name`. Note that `[*]` is removed since you don't want all array elements, you want only the ones where the name is `"ztest"`. I'm going to close this for now since it seems your problem is solved.
